version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend    
    volumes:
      - ./frontend/my-app:/app
      - ./frontend/my-app/node_modules:/app/node_modules

  backend:
    container_name: backend
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
          
  database:
    container_name: database
    build:
      context: ./backend/api/api
      dockerfile: Dockerfile
    ports:
      - 4000:27017
    volumes:
      - ./backend/api/api:/app
